---
version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
      exclude:
        - "ministryofjustice/*"
        - "moj-analytical-services/*"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
